name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Get EC2 Public IP
      id: get_ec2_ip
      run: |
        EC2_IP=$(terraform output -raw instance_public_ip)
        echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
        echo "✅ EC2 Public IP: $EC2_IP"

    - name: Copy Spring Boot App to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ env.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ec2-user/app"
        overwrite: true
        debug: true

    - name: Run setup.sh on EC2 to build and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          chmod +x /home/ec2-user/app/scripts/setup.sh
          sudo /home/ec2-user/app/scripts/setup.sh

    - name: Verify Deployment
      run: |
        sleep 15
        curl -v http://${{ env.EC2_IP }}
