name: Deploy Spring Boot App on EC2 (Multi-Stage)

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment Stage (dev, prod)"
        required: true
        default: "dev"

env:
  AWS_REGION: ap-south-1
  INSTANCE_TYPE: t2.micro
  KEY_NAME: prerna-key-new
  STAGE: ${{ github.event.inputs.stage }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Deploy Spring Boot App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/app
            git pull origin main
            mvn clean package
            sudo pkill -f 'java -jar' || true
            nohup java -jar target/techeazy-devops-0.0.1-SNAPSHOT.jar --server.port=80 &
